title: Better Form Docs
description: This is the docs for the automatic form system based on Monday.com for Alithea Genomics.
theme: just-the-docs

url: https://maochengxu.github.io/AutoForm-docs

color_scheme: blue

aux_links:
  Project Repository: https://github.com/maochengxu/AutoForm

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red